name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dotnet env
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          include-prerelease: true
        
        
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
